version: '3.8'

services:
  volleyball:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    networks:
      - traefik_web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.volleyball.rule=Host(`volleyball.homelab`, `volleyball.oesterlin.dev`)'
      - 'traefik.http.services.volleyball.loadbalancer.server.port=3000'
      - 'traefik.http.middlewares.volleyball.compress=true'
      - "traefik.http.middlewares.volleyball.plugin.httpCache.maxTtl=600"
      - "traefik.http.middlewares.volleyball.plugin.httpCache.memory.limit=500Mi"
      - "traefik.http.middlewares.volleyball.plugin.httpCache.excludedResponseCodes=300-599"
    env_file:
      - .env.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/scheduler"]
      interval: 30s
      timeout: 120s
      retries: 3
    environment:
      - MIKRO_ORM_DB_NAME=volleyball
      - MIKRO_ORM_HOST=postgres
      - MIKRO_ORM_PASSWORD=password
      - MIKRO_ORM_PORT=5432
      - MIKRO_ORM_USER=postgres
    
networks:
  traefik_web:
    external: true