version: '3.8'

services:
  volleyball:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    networks:
      - traefik_web
    environment:
      - ORIGIN=https://volleyball.oesterlin.dev
    # sqllite db file
    volumes:
      - ./db:/app/db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.volleyball.rule=Host(`volleyball.homelab`)'
      - 'traefik.http.services.volleyball.loadbalancer.server.port=3000'


networks:
  traefik_web:
    external: true