version: '3.8'

services:
  # volleyball:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env.local
  #   environment:
  #     - MIKRO_ORM_DB_NAME=volleyball
  #     - MIKRO_ORM_HOST=postgres
  #     - MIKRO_ORM_PASSWORD=password
  #     - MIKRO_ORM_PORT=5432
  #     - MIKRO_ORM_USER=postgres

  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    restart: always

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: volleyball