version: '3.8'

services:
  volleyball:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    networks:
      - traefik_web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.volleyball.rule=Host(`volleyball.homelab`)'
      - 'traefik.http.services.volleyball.loadbalancer.server.port=3000'
    env_file:
      - .env.local

  scheduler:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: node scheduler/build/index.js
    networks:
      - traefik_web
    env_file:
      - .env.local

networks:
  traefik_web:
    external: true