version: '3.8'

services:
  volleyball:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env.docker
  
  scheduler:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: node scheduler/build/index.js
    env_file:
      - .env.docker

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: volleyball