version: '3.8'

services:
  volleyball:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.volleyball.rule=Host(`volleyball.homelab`, `volleyball.oesterlin.dev`)'
      - 'traefik.http.services.volleyball.loadbalancer.server.port=3000'
      - 'traefik.http.middlewares.volleyball.compress=true'
      - "traefik.http.middlewares.volleyball.plugin.httpCache.maxTtl=600"
      - "traefik.http.middlewares.volleyball.plugin.httpCache.memory.limit=500Mi"
      - "traefik.http.middlewares.volleyball.plugin.httpCache.excludedResponseCodes=300-599"
    env_file:
      - ./server/.env.local
    environment:
      - MIKRO_ORM_DB_NAME=volleyball
      - MIKRO_ORM_HOST=postgres
      - MIKRO_ORM_PASSWORD=password
      - MIKRO_ORM_PORT=5432
      - MIKRO_ORM_USER=postgres
    
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: volleyball
  

volumes:
  data: