version: '3.8'

services:
  volleyball:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    networks:
      - traefik_web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.volleyball.rule=Host(`volleyball.homelab`, `volleyball.oesterlin.dev`)'
      - 'traefik.http.services.volleyball.loadbalancer.server.port=3000'
      - 'traefik.http.middlewares.volleyball.compress=true'

    env_file:
      - .env.local
    environment:
      - MIKRO_ORM_DB_NAME=volleyball
      - MIKRO_ORM_HOST=postgres
      - MIKRO_ORM_PASSWORD=password
      - MIKRO_ORM_PORT=5432
      - MIKRO_ORM_USER=postgres
    
  scheduler: 
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    restart: always
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true