version: '3.8'

services:
  volleyball:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    # ports:
    #   - 3000:3000
    networks:
      - traefik_web
    volumes:
      - ./db:/app/db:z
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.volleyball.rule=Host(`volleyball.homelab`)'
      - 'traefik.http.services.volleyball.loadbalancer.server.port=3000'


networks:
  traefik_web:
    external: true