name: My Deployment

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master

      - name: stop running containers
        continue-on-error: true
        run: docker-compose down --remove-orphans

      - name: Run all containers
        run: docker-compose up --build -d
