name: My Deployment

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: stop running containers
        continue-on-error: true
        run: docker compose down --remove-orphans

      - uses: actions/checkout@master

      - name: Run all containers
        run: |
          echo "VITE_VAPID_PUBLIC=${{ secrets.VITE_VAPID_PUBLIC }}" >> .env.local
          echo "VAPID_PRIVATE=${{ secrets.VAPID_PRIVATE }}" >> .env.local
          echo "MIKRO_ORM_DB_NAME=volleyball" >> .env.local
          echo "MIKRO_ORM_HOST=database" >> .env.local
          echo "MIKRO_ORM_PASSWORD=password" >> .env.local
          echo "MIKRO_ORM_PORT=5432" >> .env.local
          echo "MIKRO_ORM_USER=postgres" >> .env.local
          cat .env.local

          docker compose -f docker-compose.prod.yaml up --build -d 
